# logging-deploy.yml

name: Java CI with Gradle

on:
  release:
    types: [push] # (1) push시 자동으로 실행
  push:
    branches: [main] # (2) main 브랜치에서 동작
  workflow_dispatch: # 수동으로도 실행이 가능

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read 
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash
        
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: lsh901673@gmail.com
          # from email name
          from: LEE-sh1673
